### Get organizations

GET http://localhost:3000/organization

### Insert organization
POST http://localhost:3000/organization
Content-Type: application/json

{
  "name": "Organization 4"
}

### Update organization
PATCH http://localhost:3000/organization/885079822218821633
Content-Type: application/json

{
  "name": "Organization 5"
}

### Delete organization
DELETE http://localhost:3000/organization/885079783026491393


### Get metrics
GET http://localhost:3000/tribe/885127672539447297