### Get organizations

GET http://localhost:3000/organization

### Insert organization
POST http://localhost:3000/organization
Content-Type: application/json

{
  "name": "Organization 4"
}

### Update organization
PATCH http://localhost:3000/organization/885302649400524801
Content-Type: application/json

{
  "name": "Organization 11"
}

### Delete organization
DELETE http://localhost:3000/organization/885385577359572993


### Get metrics
GET http://localhost:3000/tribe/1/metrics

### Get report
GET http://localhost:3000/tribe/1/report