### Get organizations

GET http://localhost:3000/organization

### Insert organization
POST http://localhost:3000/organization
Content-Type: application/json

{
  "name": "Organization 4"
}

### Delete organization
DELETE http://localhost:3000/organization/885079783026491393
